config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users
  get 'home/about'
  root 'companies#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :user
	has_one_attached :image

	validates :email, uniqueness: true , presence: true
	validates :website, :uniqueness => true
	validates :company_name, presence: true
	validates :phone_no, uniqueness: true, format: { with: /\A[0-9]*\Z/,
    message: "only number" }
	
	
	

	COUNTRY_LIST = ["Myanmar","Japan"]
	INDUSTRY_LIST = ["Agriculture, Forestry, Fishing and Hunting","Mining","Utilities","Educational Services","IT&Computer","Wholesale Trade"]
	STATE_LIST = ["Yangon","Mandalay","kayin","Kachin","Shan"]
	TOWNSHIP_LIST = ["Hlaing","Latha","Dala","Kamayout","Sanchaung"]
	FOUNDED_LIST = ["2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]

	
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 8..10
         

         has_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		@company = Company.new
  new_company_path(@company) 
end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,only: [:edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    if params[:search_key]
      @companies = Company.where("email LIKE ? OR industry LIKE ?", 
      "%#{params[:search_key]}%","%#{params[:search_key]}%")
    else
      @companies = Company.all
    end
   end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    
    @company = current_user.companies.build
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = current_user.companies.build(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def correct_user
    @company =current_user.companies.find_by(id: params[:id])
    redirect_to companies_path, notice: "Not Authorized To Edit This Friend" if @company.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:company_name, :country, :email, :website, :facebook, :founded, :Number_of_employee, :industry, :address, :phone_no, :state, :township, :description, :image, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
<br/>
<% if company.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible fade show" role="alert">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    </div>
  <% end %>





<div class = "container">
<div class="card">
  <h5 class="card-header p-3 mb-2 bg-info text-white">New Company</h5>
  <div class="card-body p-3 mb-2 bg-light text-dark">
    <form>

     <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :image %><span class="text-danger">*</span>
      <%= form.file_field :image,class:"form-control" %>
    </div>
  </div> 
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :company_name %><span class="text-danger">*</span>
      <%= form.text_field :company_name,class:"form-control",placeholder:"Pleace enter the company name", maxlength:"45" %>

    </div>
    <div class="form-group col-md-6">
      <%= form.label :country %><span class="text-danger">*</span>
      
     <%= form.select :country, Company::COUNTRY_LIST,  { prompt: t("companies.counties.Select"), selected: @company.country }, { class: "form-control", :required => true } %>
    
    </div>
  </div>
 

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :email %><span class="text-danger">*</span>
      <%= form.email_field :email,class:"form-control",placeholder:"email@gmail.com"%>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :website %>
      <%= form.text_field :website,class:"form-control",placeholder:"https://www.website.com" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :facebook %>
      <%= form.text_field :facebook,class:"form-control",placeholder:"https://www.facebook.com" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :phone_no %><span class="text-danger">*</span>
      <%= form.text_field :phone_no,class:"form-control",placeholder:"09-", maxlength:"15" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :address %><span class="text-danger">*</span>
      <%= form.text_area :address,class:"form-control",placeholder:"Address", :required => true  %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :Number_of_employee %>
      <%= form.number_field :Number_of_employee,class:"form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :industry %>  <span class="text-danger">*</span>  

      <%= form.select :industry, Company::INDUSTRY_LIST,  { prompt: t("companies.counties.Select"), selected: @company.industry }, { class: "form-control", :required => true } %>
     

    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :state %>
     
<%= form.select :state, Company::STATE_LIST,  { prompt: t("companies.counties.Select"), selected: @company.state }, { class: "form-control"} %>

    </div>
    <div class="form-group col-md-6">
      <%= form.label :township %>
      <%= form.select :township, Company::TOWNSHIP_LIST,  { prompt: t("companies.counties.Select"), selected: @company.township }, { class: "form-control"} %>      
    </div>
    </div>

    
  <div class="form-row">
    
     <div class="form-group col-md-6">
      <%= form.label :founded %>
      <%= form.select :founded, Company::FOUNDED_LIST,  { prompt: t("companies.counties.Select"), selected: @company.founded }, { class: "form-control", :required => true } %>      
     
    </div>
    </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :description %>
      <%= form.text_area :description,class:"form-control" %>   

    </div>
  </div>

  <div class="field form-group">    
    <%= form.number_field :user_id, 
    id: :company_user_id, class:"form-control",
    value: current_user.id, type: :hidden %>
  </div>  
  <br/>

  <div class="actions">
      <%= form.submit class:"btn btn-info"%>       

  </div>
</form>
  </div>
</div>
</div>
  
<% end %>

app/views/companies/edit.html.erb
<br/>

<%= render 'form', company: @company %>
 <br/>
 <center>
    <%= link_to 'Back', companies_path, class:"btn btn-dark" %>|

    <%= link_to 'Show', @company, class:"btn btn-info" %> 
  
</center>
<br/>
<br/>

app/views/companies/index.html.erb
<% if user_signed_in? %>



<br/>
<div class="container">
     
<form action="<%= companies_path %>">
      <input type="text" placeholder="Enter" name="search_key" >
  <button type="submit" class="btn btn-info">Search</button>
</form>
<br/>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-info">
    <tr>
      <th>Company name</th>
      <th>Country</th>
      <th>Email</th>
      
      <th>Industry</th>
      <th>Address</th>
      <th>Phone no</th>
      <th>State</th>
      <th>Township</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @companies.each do |company| %>
    <% if company.user == current_user %> 
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.country %></td>
        <td><%= company.email %></td>
        
        <td><%= company.industry %></td>
        <td><%= company.address %></td>
        <td><%= company.phone_no %></td>
        <td><%= company.state %></td>
        <td><%= company.township %></td>
        
        <td ><%= link_to 'Show', company, class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_company_path(company), class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, class:"btn btn-info" %>
<% else -%>

<h1>Hello My App</h1>
Hi hello
<% end -%>
</div>

app/views/companies/new.html.erb
<br/>
<%= render 'form', company: @company %>
<br/>
<center>
 <%= link_to 'Back', companies_path, class:"btn btn-dark" %>   
</center>
<br/>
<br/>

app/views/companies/show.html.erb
 
<div class="container">
<div class="card">
  <div class="card-header p-3 mb-2 bg-info text-white">
    <p style="font-size: 25px"> <strong>Detail Company Information</strong></p>
  </div>
  <div class="card-body p-3 mb-2 bg-light text-dark">
    <form>




      <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Company name:</strong>
        <%= @company.company_name %>
       </p>
       </div>
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Country:</strong>
        <%= @company.country%>
      </p>
       </div>
      </div>


       <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Email:</strong>
        <%= @company.email %>
       </p>
       </div>
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Website:</strong>
        <%= @company.website %>
       </p>
       </div>
      </div>


       <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Facebook:</strong>
        <%= @company.facebook %>
       </p>
       </div>
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Founded:</strong>
        <%= @company.founded %>
       </p>
       </div>
      </div>


      <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Number of employee:</strong>
        <%= @company.Number_of_employee %>
        </p>
       </div>
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Industry:</strong>
        <%= @company.industry %>
        </p>
       </div>
      </div>


      <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Address:</strong>
        <%= @company.address %>
        </p>
       </div>
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Phone no:</strong>
        <%= @company.phone_no %>
      </p>
       </div>
      </div>


      <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>State:</strong>
        <%= @company.state %>
        </p>
       </div>
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
        <strong>Township:</strong>
        <%= @company.township %>
        </p>
       </div>
      </div>


      <div class="form-row">
       <div class="form-group col-md-6">
        <p style="font-size: 20px">
       <strong>Description:</strong>
       <%= @company.description %>
       </p>
       </div>
      </div>

      <div class="form-row">
       <div class="form-group col-md-6">
        <p>
       <strong>Image:</strong>
       <%= link_to image_tag(@company.image,style: "width:100%"), companies_path %>
       </p>
       </div>
      </div>


      <center>
    <%= link_to 'Edit', edit_company_path(@company), class:"btn btn-info" %> |
<%= link_to 'Back', companies_path, class:"btn btn-dark" %>
  </center>

</form>
  </div>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Company', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
             

          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Company", new_company_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, 
            method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
          </li>
         
          <% else %>

          <li class="nav-item">
            <%= link_to "Sing Up",  new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <%end%>  
      
    </ul>
  
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello My App</h1>
Hi hello

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head> 

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">     

    <title>Recruitment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     
  </head> 

  <body>
    <%= render 'home/header'%>
    <div class="container">
        <br/>
        <% if notice %>
           <%= render 'layouts/alert'%>
        <% end %>    

    <%= yield %>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>